In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("imdb_top_1000.csv")

Inspection

In [4]:
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   str
 10  Star1          1000 non-null   str
 11  Star2          1000 non-null   str
 12  Star3          1000 non-null   str
 13  Star4          1000 non-null   str
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    str
dtypes: float64(2), int64(1), str(13)
memory usage: 125.1 KB

In [5]:
#samples

df.head(2)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"

In [6]:
#checking if a movie is referenced more than once
df['Poster_Link'].is_unique

True

Fixing incorrect column data types

In [7]:
#fixing gross column, dropping empty ones

df["Gross"] = pd.to_numeric(
    df["Gross"].str.replace(",", "", regex=False),
    errors="coerce"
).astype("Int64")

df.dropna(subset="Gross", inplace=True)

In [8]:
#fixing runtime column

df["Runtime"] = (
    df["Runtime"]
    .str.replace(" min", "", regex=False)
    .astype("Int64")
)

In [9]:
#fixing release year column

df["Released_Year"] = pd.to_numeric(df["Released_Year"], errors="coerce").astype("Int64")

In [10]:
df.describe()

,Released_Year,Runtime,IMDB_Rating,Meta_score,No_of_Votes,Gross
count,830.0,831.0,831.000000,750.000000,8.310000e+02,831.0
mean,1993.918072,124.078219,7.946931,77.460000,3.152499e+05,68034750.873646
std,21.147778,27.501455,0.283204,12.493967,3.436443e+05,109750043.192185
min,1921.0,45.0,7.600000,28.000000,2.508800e+04,1305.0
25%,1984.0,104.0,7.700000,70.000000,7.143000e+04,3253559.0
50%,2000.0,120.0,7.900000,78.000000,1.867340e+05,23530892.0
75%,2010.0,138.0,8.100000,86.000000,4.457210e+05,80750893.5
max,2019.0,242.0,9.300000,100.000000,2.343110e+06,936662225.0

In [11]:
#adding another column based on the gross column

bins = [0, 10_000_000, 50_000_000, 100_000_000, float("inf")]
labels = ["Low", "Moderate", "High", "Blockbuster"]

df["gross_category"] = pd.cut(
    df["Gross"],
    bins=bins,
    labels=labels
)

In [12]:
print("Rows:", len(df))
print("\nMissing values:")
print(df.isna().sum())

Rows: 831

Missing values:
Poster_Link        0
Series_Title       0
Released_Year      1
Certificate       46
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score        81
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross              0
gross_category     0
dtype: int64

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 831 entries, 0 to 997
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Poster_Link     831 non-null    str
 1   Series_Title    831 non-null    str
 2   Released_Year   830 non-null    Int64
 3   Certificate     785 non-null    str
 4   Runtime         831 non-null    Int64
 5   Genre           831 non-null    str
 6   IMDB_Rating     831 non-null    float64
 7   Overview        831 non-null    str
 8   Meta_score      750 non-null    float64
 9   Director        831 non-null    str
 10  Star1           831 non-null    str
 11  Star2           831 non-null    str
 12  Star3           831 non-null    str
 13  Star4           831 non-null    str
 14  No_of_Votes     831 non-null    int64
 15  Gross           831 non-null    Int64
 16  gross_category  831 non-null    category
dtypes: Int64(3), category(1), float64(2), int64(1), str(10)
memory usage: 113.8 KB

In [14]:
df.to_csv("cleaned_data.csv", index=False)